[package]
name = "hmac-predicate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
form_urlencoded = "*"
hex = "*"
hmac = "*"
http = "*"
sha2 = "*"
thiserror = "*"
tower = { version = "*", features = ["filter"] }
